#!/bin/sh

set -e

. /usr/share/debconf/confmodule
TEMPLATE="/usr/share/webobjects/defaults.template"
CONFFILE="/etc/default/webobjects"
WOTASKD_CONF_DIR="/var/lib/webobjects/Library/WebObjects/Configuration"

[ -x /etc/init.d/wotaskd ] && invoke-rc.d wotaskd stop
[ -x /etc/init.d/javamonitor ] && invoke-rc.d javamonitor stop

case "$1" in
    configure)
	# Generate $CONFFILE from debconf seetings and $TEMPLATE
	db_fget webobjects/local_wo_dmg seen || true
	if [ "$RET" != "true" ]; then
		db_input high webobjects/local_wo_dmg || true
		db_go || true
		db_get webobjects/local_wo_dmg
		if [ "$RET" = "true" ]; then
			valid=
			while [ ! "$valid" ] ; do
				db_input high webobjects/local_wo_dmg_base_url || true
				[ "$RET" = 30 ] && valid=1
				db_go || true
				db_get webobjects/local_wo_dmg_base_url || true
				case "$RET" in
					ftp://?*|http://?*|https://?*)
						valid=1
						;;
					?*)
						db_input high webobjects/local_wo_dmg_base_url_not_supported || true
						;;
				esac
			done
		fi
	fi
	db_get webobjects/username && WEBOBJECTS_USER="$RET" || WEBOBJECTS_USER="webobjects"
	db_get webobjects/groupname && WEBOBJECTS_GROUP="$RET" || WEBOBJECTS_GROUP="webobjects"
	if db_get webobjects/local_wo_dmg && [ "$RET" = "true" ] ; then
		db_get webobjects/local_wo_dmg_base_url && WEBOBJECTS_URL="$RET"
	fi

	tmpfile=`mktemp /tmp/webobjects.XXXXXXXXXX`
	chmod 644 $tmpfile
	cat $TEMPLATE \
		| sed "s%^WEBOBJECTS_USER=.*$%WEBOBJECTS_USER=$WEBOBJECTS_USER%" \
		| sed "s%^WEBOBJECTS_GROUP=.*$%WEBOBJECTS_GROUP=$WEBOBJECTS_GROUP%" \
		| sed "s%^WEBOBJECTS_URL=.*$%WEBOBJECTS_URL=$WEBOBJECTS_URL%" \
		>> $tmpfile
	ucf --debconf-ok --sum-file /usr/share/webobjects/defaults.md5sum $tmpfile $CONFFILE
	rm -f $tmpfile

	if ! getent group "$WEBOBJECTS_GROUP" >/dev/null 2>&1 ; then
		addgroup --system "$WEBOBJECTS_GROUP" --quiet
	fi
	if ! id "$WEBOBJECTS_USER" >/dev/null 2>&1 ; then
		adduser --system --home "$WOTASKD_CONF_DIR" \
			--no-create-home --ingroup "$WEBOBJECTS_GROUP" \
			--disabled-password --shell /bin/false \
			"$WEBOBJECTS_USER"
	fi
	if update-webobjects --install --fast ; then
		[ -d "$WOTASKD_CONF_DIR" ] || \
			install -m0700 -o ${WEBOBJECTS_USER} -g ${WEBOBJECTS_GROUP} -d "$WOTASKD_CONF_DIR"
		update-webobjects --status
		update-rc.d wotaskd defaults 92 08 >/dev/null
		invoke-rc.d wotaskd start || true
		update-rc.d javamonitor defaults 93 07 >/dev/null
		invoke-rc.d javamonitor start || true
	else
		db_fset webobjects/local_wo_dmg seen false
		exit 1
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
