#!/bin/sh

set -e

[ -x /etc/init.d/wotaskd ] && invoke-rc.d wotaskd stop
[ -x /etc/init.d/javamonitor ] && invoke-rc.d javamonitor stop

case "$1" in
    remove|upgrade|deconfigure)
	update-webobjects --uninstall || true
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
